### ISSUE TITLE
PLease, instruct me where to put the class. 

### ISSUE THREAD

**Issue by parmonov98** [maksa988/laravel-freekassa#8]
https://github.com/maksa988/laravel-freekassa/blob/70ab8836f9dd4c98fa3d571ded44a2bfcc6c9b06/src/FreeKassa.php#L2

Please, instruct me where to put the class. I don't know where to put and how to use it. The package doe not supported in Laravel 8. 

I create FreeKassProvider and created freekassa.php in config folder. 
What is the next step?

**Comment by maksa988** [comment]
Add support by the end of today.

**Comment by maksa988** [comment]
For Laravel 8 use new v4.0.0 version. Master branch.
