### ISSUE TITLE
what to write for callback?

### ISSUE THREAD

**Issue by parmonov98** [maksa988/laravel-freekassa#9]
You wrote null, how should we change? 
https://i.imgur.com/VZCDQ6q.png

I uncommented the lines and removed null s. 
https://i.imgur.com/fidTbs3.png as here.

I get nothing https://imgur.com/GE6c1mC when I send GET params manually.  What am I doing? I'm just wondering even if tried by yourself?

because, payment handler method in freekassacontroller does not get the expected result. 

https://i.imgur.com/T58t5Gs.png

![image](https://user-images.githubusercontent.com/24564577/95669898-b38c8080-0b9e-11eb-837c-19c4c3fd3e53.png)

I think, you have to recheck and make sure it works. I tested this in trial mode of free-kassa.

**Comment by maksa988** [comment]
You should past your controller name and action. An example is indicated in the comment near the parameter

`FreeKassaController@paidOrder` - example. Not only `paidOrder`.
